"""soft delete de paciente, comissao do profissional e 2fa do usuario

Revision ID: 19e6081c11e4
Revises: 6585a11d46dd
Create Date: 2026-06-21 16:38:54.671243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19e6081c11e4'
down_revision = '6585a11d46dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excluido_em', sa.DateTime(), nullable=True))

    with op.batch_alter_table('profissional_estetico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comissao_percentual', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('totp_enabled')
        batch_op.drop_column('totp_secret')

    with op.batch_alter_table('profissional_estetico', schema=None) as batch_op:
        batch_op.drop_column('comissao_percentual')

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('excluido_em')

    # ### end Alembic commands ###
