"""consentimento lgpd do paciente e campos genericos de auditoria

Revision ID: 6585a11d46dd
Revises: cf6352b884f4
Create Date: 2026-06-21 16:02:14.675556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6585a11d46dd'
down_revision = 'cf6352b884f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('target_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        # server_default é necessário aqui: a tabela já tem linhas em produção, e
        # Postgres exige um valor para preenchê-las ao adicionar uma coluna NOT NULL.
        # Pacientes existentes ficam com consentimento_lgpd=False (correto: não há
        # registro de que consentiram sob este novo controle).
        batch_op.add_column(sa.Column('consentimento_lgpd', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('data_consentimento_lgpd', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ip_consentimento_lgpd', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('ip_consentimento_lgpd')
        batch_op.drop_column('data_consentimento_lgpd')
        batch_op.drop_column('consentimento_lgpd')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_column('ip_address')
        batch_op.drop_column('target_id')
        batch_op.drop_column('target_type')

    # ### end Alembic commands ###
