"""unidades, token de api, assinatura eletronica de consentimento

Revision ID: 6e76f43c692a
Revises: 19e6081c11e4
Create Date: 2026-06-21 17:04:36.700191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e76f43c692a'
down_revision = '19e6081c11e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('endereco', sa.String(length=300), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), server_default=sa.true(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assinatura_consentimento', sa.Text(), nullable=True))

    with op.batch_alter_table('profissional_estetico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unidade_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_profissional_estetico_unidade_id', 'unidade', ['unidade_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('api_token', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint('uq_user_api_token', ['api_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_api_token', type_='unique')
        batch_op.drop_column('api_token')

    with op.batch_alter_table('profissional_estetico', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profissional_estetico_unidade_id', type_='foreignkey')
        batch_op.drop_column('unidade_id')

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_column('assinatura_consentimento')

    op.drop_table('unidade')
    # ### end Alembic commands ###
