"""esquema inicial

Revision ID: 75c7eca808f5
Revises: 
Create Date: 2026-06-19 16:12:25.948263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75c7eca808f5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.create_table('paciente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=150), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('historico_medico', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('servico_estetico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_servico', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('duracao_minutos', sa.Integer(), nullable=True),
    sa.Column('preco', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome_servico')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('agendamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_hora_agendamento', sa.DateTime(), nullable=False),
    sa.Column('motivo_agendamento', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('data_hora_lembrete_enviado', sa.DateTime(), nullable=True),
    sa.Column('metodo_lembrete', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anamnese',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_anamnese', sa.DateTime(), nullable=True),
    sa.Column('queixa_principal', sa.Text(), nullable=True),
    sa.Column('historico_doenca_atual', sa.Text(), nullable=True),
    sa.Column('historico_patologico_pregresso', sa.Text(), nullable=True),
    sa.Column('historico_familiar', sa.Text(), nullable=True),
    sa.Column('habitos_vida', sa.Text(), nullable=True),
    sa.Column('medicamentos_uso', sa.Text(), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_atendimento', sa.DateTime(), nullable=True),
    sa.Column('anotacoes', sa.Text(), nullable=True),
    sa.Column('foto_antes', sa.String(length=200), nullable=True),
    sa.Column('foto_depois', sa.String(length=200), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_user_id', sa.Integer(), nullable=True),
    sa.Column('target_username', sa.String(length=80), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exame_fisico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_exame', sa.DateTime(), nullable=True),
    sa.Column('estado_geral', sa.String(length=100), nullable=True),
    sa.Column('pele_mucosas', sa.Text(), nullable=True),
    sa.Column('aparelho_respiratorio', sa.Text(), nullable=True),
    sa.Column('aparelho_cardiovascular', sa.Text(), nullable=True),
    sa.Column('abdome', sa.Text(), nullable=True),
    sa.Column('sistema_nervoso', sa.Text(), nullable=True),
    sa.Column('sistema_musculo_esqueletico', sa.Text(), nullable=True),
    sa.Column('pressao_arterial', sa.String(length=20), nullable=True),
    sa.Column('frequencia_cardiaca', sa.String(length=20), nullable=True),
    sa.Column('temperatura', sa.String(length=20), nullable=True),
    sa.Column('saturacao_o2', sa.String(length=20), nullable=True),
    sa.Column('observacoes_gerais', sa.Text(), nullable=True),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profissional_estetico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('especialidades', sa.String(length=500), nullable=True),
    sa.Column('telefone_contato', sa.String(length=20), nullable=True),
    sa.Column('disponibilidade_status', sa.String(length=50), nullable=True),
    sa.Column('data_inicio_ferias', sa.Date(), nullable=True),
    sa.Column('data_fim_ferias', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agendamento_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('servico_id', sa.Integer(), nullable=False),
    sa.Column('data_agendamento', sa.DateTime(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('avaliacao', sa.Integer(), nullable=True),
    sa.Column('comentario_cliente', sa.Text(), nullable=True),
    sa.Column('data_hora_lembrete_enviado', sa.DateTime(), nullable=True),
    sa.Column('metodo_lembrete', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissional_estetico.id'], ),
    sa.ForeignKeyConstraint(['servico_id'], ['servico_estetico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('horario_atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profissional_id', sa.Integer(), nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=True),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('intervalo_minutos', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['profissional_id'], ['profissional_estetico.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('procedimento_atendimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_procedimento', sa.String(length=200), nullable=False),
    sa.Column('observacoes_procedimento', sa.Text(), nullable=True),
    sa.Column('atendimento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['atendimento_id'], ['atendimento.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procedimento_atendimento')
    op.drop_table('horario_atendimento')
    op.drop_table('agendamento_servico')
    op.drop_table('profissional_estetico')
    op.drop_table('exame_fisico')
    op.drop_table('audit_log')
    op.drop_table('atendimento')
    op.drop_table('anamnese')
    op.drop_table('agendamento')
    op.drop_table('user')
    op.drop_table('servico_estetico')
    op.drop_table('paciente')
    op.drop_table('configuracao')
    # ### end Alembic commands ###
