"""super admin da plataforma

Revision ID: a24c28cd154e
Revises: a2f6daf42880
Create Date: 2026-06-20 15:37:30.263307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24c28cd154e'
down_revision = 'a2f6daf42880'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default trocado de sa.text('0') (autogerado) para sa.false():
    # '0' funciona como default de boolean no SQLite, mas o Postgres não
    # aceita inteiro como default de coluna boolean (erro de tipo).
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eh_super_admin', sa.Boolean(), server_default=sa.false(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('eh_super_admin')

    # ### end Alembic commands ###
