"""multi-tenant estabelecimentos

Revision ID: a2f6daf42880
Revises: d39eeef51f50
Create Date: 2026-06-19 17:33:36.440885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f6daf42880'
down_revision = 'd39eeef51f50'
branch_labels = None
depends_on = None


def upgrade():
    # ATENÇÃO: passo destrutivo, adicionado manualmente (não gerado pelo autogenerate).
    # As tabelas abaixo recebem uma coluna estabelecimento_id NOT NULL nesta mesma
    # migration. Não existe "estabelecimento" para linhas que já existiam antes do
    # multi-tenant, então elas são removidas aqui. Só é seguro porque, neste momento,
    # essas tabelas só contêm dados de demonstração/desenvolvimento — nunca dados
    # reais de produção (nada foi implantado ainda). Ordem respeita dependências de FK.
    for tabela in (
        'procedimento_atendimento', 'atendimento', 'anamnese', 'exame_fisico',
        'agendamento_servico', 'servico_estetico', 'horario_atendimento', 'profissional_estetico',
        'paciente', 'audit_log', 'user',
    ):
        op.execute(f'DELETE FROM {tabela}')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('logo_filename', sa.String(length=200), nullable=True),
    sa.Column('cor_novos_pacientes', sa.String(length=50), nullable=True),
    sa.Column('cor_cabecalho', sa.String(length=50), nullable=True),
    sa.Column('email_clinica', sa.String(length=120), nullable=True),
    sa.Column('senha_email_clinica', sa.String(length=200), nullable=True),
    sa.Column('dias_reenvio_lembrete_retorno', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trial_termina_em', sa.DateTime(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('configuracao')
    op.drop_table('agendamento')
    with op.batch_alter_table('agendamento_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_agendamento_servico_estabelecimento_id', 'estabelecimento', ['estabelecimento_id'], ['id'])

    with op.batch_alter_table('anamnese', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_anamnese_estabelecimento_id', 'estabelecimento', ['estabelecimento_id'], ['id'])

    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_atendimento_estabelecimento_id', 'estabelecimento', ['estabelecimento_id'], ['id'])

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_audit_log_estabelecimento_id', 'estabelecimento', ['estabelecimento_id'], ['id'])

    with op.batch_alter_table('exame_fisico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_exame_fisico_estabelecimento_id', 'estabelecimento', ['estabelecimento_id'], ['id'])

    with op.batch_alter_table('horario_atendimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_horario_atendimento_estabelecimento_id', 'estabelecimento', ['estabelecimento_id'], ['id'])

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_paciente_estabelecimento_cpf', ['estabelecimento_id', 'cpf'])
        batch_op.create_foreign_key('fk_paciente_estabelecimento_id', 'estabelecimento', ['estabelecimento_id'], ['id'])

    with op.batch_alter_table('profissional_estetico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_profissional_estetico_estabelecimento_id', 'estabelecimento', ['estabelecimento_id'], ['id'])

    with op.batch_alter_table('servico_estetico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_servico_estabelecimento_nome', ['estabelecimento_id', 'nome_servico'])
        batch_op.create_foreign_key('fk_servico_estetico_estabelecimento_id', 'estabelecimento', ['estabelecimento_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estabelecimento_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_user_estabelecimento_id', 'estabelecimento', ['estabelecimento_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_estabelecimento_id', type_='foreignkey')
        batch_op.drop_column('estabelecimento_id')

    with op.batch_alter_table('servico_estetico', schema=None) as batch_op:
        batch_op.drop_constraint('fk_servico_estetico_estabelecimento_id', type_='foreignkey')
        batch_op.drop_constraint('uq_servico_estabelecimento_nome', type_='unique')
        batch_op.drop_column('estabelecimento_id')

    with op.batch_alter_table('profissional_estetico', schema=None) as batch_op:
        batch_op.drop_constraint('fk_profissional_estetico_estabelecimento_id', type_='foreignkey')
        batch_op.drop_column('estabelecimento_id')

    with op.batch_alter_table('paciente', schema=None) as batch_op:
        batch_op.drop_constraint('fk_paciente_estabelecimento_id', type_='foreignkey')
        batch_op.drop_constraint('uq_paciente_estabelecimento_cpf', type_='unique')
        batch_op.drop_column('estabelecimento_id')

    with op.batch_alter_table('horario_atendimento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_horario_atendimento_estabelecimento_id', type_='foreignkey')
        batch_op.drop_column('estabelecimento_id')

    with op.batch_alter_table('exame_fisico', schema=None) as batch_op:
        batch_op.drop_constraint('fk_exame_fisico_estabelecimento_id', type_='foreignkey')
        batch_op.drop_column('estabelecimento_id')

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_audit_log_estabelecimento_id', type_='foreignkey')
        batch_op.drop_column('estabelecimento_id')

    with op.batch_alter_table('atendimento', schema=None) as batch_op:
        batch_op.drop_constraint('fk_atendimento_estabelecimento_id', type_='foreignkey')
        batch_op.drop_column('estabelecimento_id')

    with op.batch_alter_table('anamnese', schema=None) as batch_op:
        batch_op.drop_constraint('fk_anamnese_estabelecimento_id', type_='foreignkey')
        batch_op.drop_column('estabelecimento_id')

    with op.batch_alter_table('agendamento_servico', schema=None) as batch_op:
        batch_op.drop_constraint('fk_agendamento_servico_estabelecimento_id', type_='foreignkey')
        batch_op.drop_column('estabelecimento_id')

    op.create_table('agendamento',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_hora_agendamento', sa.DATETIME(), nullable=False),
    sa.Column('motivo_agendamento', sa.VARCHAR(length=200), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=True),
    sa.Column('observacoes', sa.TEXT(), nullable=True),
    sa.Column('paciente_id', sa.INTEGER(), nullable=False),
    sa.Column('data_hora_lembrete_enviado', sa.DATETIME(), nullable=True),
    sa.Column('metodo_lembrete', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['paciente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configuracao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('chave', sa.VARCHAR(length=50), nullable=False),
    sa.Column('valor', sa.VARCHAR(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave')
    )
    op.drop_table('estabelecimento')
    # ### end Alembic commands ###
