"""cores customizaveis do estabelecimento (primaria e acento)

Revision ID: cf6352b884f4
Revises: a54da3e9f22e
Create Date: 2026-06-20 22:29:49.066594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf6352b884f4'
down_revision = 'a54da3e9f22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_primaria', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('cor_acento', sa.String(length=7), nullable=True))
        batch_op.drop_column('cor_cabecalho')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cor_cabecalho', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('cor_acento')
        batch_op.drop_column('cor_primaria')

    # ### end Alembic commands ###
