"""lembrete de retorno por procedimento

Revision ID: d39eeef51f50
Revises: 75c7eca808f5
Create Date: 2026-06-19 16:31:43.813634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39eeef51f50'
down_revision = '75c7eca808f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agendamento_servico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_ultimo_lembrete_retorno_enviado', sa.DateTime(), nullable=True))

    with op.batch_alter_table('servico_estetico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_lembrete_retorno', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servico_estetico', schema=None) as batch_op:
        batch_op.drop_column('dias_lembrete_retorno')

    with op.batch_alter_table('agendamento_servico', schema=None) as batch_op:
        batch_op.drop_column('data_ultimo_lembrete_retorno_enviado')

    # ### end Alembic commands ###
